config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :incidents do
    collection do
	  get 'create_incident'
	end
  end
  root :to => "incidents#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/incident.rb
class Incident < ApplicationRecord
  
  belongs_to :incident_type
  validates :description, presence: true
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
end

app/models/incident_type.rb
class IncidentType < ApplicationRecord 
  
  has_many :indents
  validates :title, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]
  before_action :set_incident_types, only: [:new, :create_incident, :create, :destroy]

 # GET /incidents/1
  # GET /incidents/1.json
  def show
  end
 
  def index 
  	@incidents = Incident.all 
  	respond_to do |format|
      format.html
      format.json
  	end
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end
  
  # GET /incidents/new
  def create_incident
    @incident = Incident.new
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_incident_types
      @incident_types = IncidentType.all
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:incident_type_id, :description,:people,:other_observers,:location,:date_time_observed,:user_name,:email, :phone,:user_role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<div class="box-body">
  <%= form_for @incident, local: true do |f| %>
    <% if incident.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>
        <ul>
        <% incident.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <h4>Lincoln High School</h4>
    </div>
     <div class="form-group">
      <%= f.label :description,"Describe issue/incident", :class => "form-group" %>
      <%= f.text_area :description, :class => "form-control", cols: 60, rows: 15 %>
    </div>

    <div class="form-group">
      <%= f.button :submit, class: 'btn btn-primary' do %>
        Submit
      <% end %>
    </div>
  <% end %>
</div>

app/views/incidents/_form_detail.html.erb
<div class = "box-body">
  <%= form_for @incident, local: true do |f| %>
    <% if incident.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

        <ul>
        <% incident.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-header">
      <h4>Lincoln High School</h4>
    </div>
    <div class="form-group">
      <%= f.label :incident_type_id, "Type of Incident" %>
      <%= f.collection_select :incident_type_id, @incident_types,:id,:title, include_blank: true, :class => "form-control" %>
    </div>
    
    <h3>Your details</h3>
    <div class="form-group">
      <%= f.label :user_name,"Name" %>
      <%= f.text_field :user_name, :class => "form-control", :required => true%>
    </div>
    <div class="form-group">
      <%= f.label :email,"Email" %>
      <%= f.text_field :email, :class => "form-control", :required => true%>
    </div>
    <div class = "form-group">
      <%= f.label :phone, "Phone" %>
      <%= f.number_field :phone, :class => "form-control", :required => true %>
    </div>
      <div class="form-group">
      <%= f.label :user_role %>
      <%= f.select :user_role, ['student', 'teacher','other staff','parent','community member'], :class => "form-control", :required => true%>
    </div>
    
     <div class="form-group">
      <%= f.label :people,"People involved" %>
      <%= f.text_field :people, placeholder: "Name and other details of people involved (student, teacher, staff, parent, 
  grade level)", :class => "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :other_observers,"Other observers if any" %>
      <%= f.text_field :other_observers, placeholder: "Name and details", :class => "form-control" %>
    </div>
    
    <div class="form-group">
      <%= f.label :date_time_observed,"Date/ Time observed" %>
      <%= f.text_field :date_time_observed, :class => "form-control", :required => true %>
    </div>
    
    <div class="form-group">
      <%= f.label :location %>
      <%= f.select :location, ['On school campuses and grounds', 'During transportation to and from school','At school-sponsored events','More details'], :class => "form-control", :required => true%>
    </div>
    
     <div class="form-group">
      <%= f.label :description,"Describe issue/incident" %>
      <%= f.text_area :description, cols: 60, rows: 15, :class => "form-control", :required => true %>
    </div>

    <div class="form-group">
      <%= f.button :submit, class: 'btn btn-primary' do %>
        Submit
      <% end %>
    </div>
  <% end %>
</div>

app/views/incidents/create_incident.html.erb
<h1>New Incident</h1>
<%= link_to 'Back', root_path, :style => "float:right" %>
<%= render 'form', incident: @incident %>
<%= link_to 'Or Submit Detailed Report', new_incident_path %>

app/views/incidents/index.html.erb
<div class = "container">
  <h3>Welcome to the Incident reporting system</h3> 
  <p><%= link_to("click here", create_incident_incidents_path())%> to report an incident</p>
</div>

app/views/incidents/new.html.erb
<h1>New Incident</h1>
<%= link_to 'Back', root_path, :style => "float:right" %>
<%= render 'form_detail', incident: @incident %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Back', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Incident Reporting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="container">
    <section>
      <p class = "header">
        <a href="<%= root_path%>">
          <h1>Incident Reporting System</h1>
        </a>
      </p>
    <%= yield %>
        </section>
  </div>

  </body>
</html>